# Ktlint configuration for RunIQ
# See: https://pinterest.github.io/ktlint/latest/rules/configuration-ktlint/

# Disabled rules
disabled_rules:
  # Allow wildcard imports for common Android/Compose imports
  - no-wildcard-imports
  # Allow Composable functions to start with uppercase
  - function-naming

# Rule configurations
indent_style: space
indent_size: 4
max_line_length: 120
insert_final_newline: true

# Android specific settings
android: true

# Import ordering
ij_kotlin_imports_layout: |
  *
  |
  java.**
  |
  javax.**
  |
  kotlin.**
  |
  ^

# Allow trailing commas
ij_kotlin_allow_trailing_comma: true
ij_kotlin_allow_trailing_comma_on_call_site: true

# Multiline expression wrapping
ij_kotlin_continuation_indent_size: 4