name: Linear Sync

on:
  issues:
    types: [opened, edited, closed, reopened]
  pull_request:
    types: [opened, edited, closed, reopened, merged]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Linear Issue Sync
        uses: linear/linear-github-sync@v1
        with:
          linear-api-key: ${{ secrets.LINEAR_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          linear-team-name: "RunIQ"
